# Generated by Django 4.0.6 on 2022-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorname', models.CharField(max_length=100)),
                ('actor_email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
