# Generated by Django 4.0.6 on 2022-07-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
