# Generated by Django 4.0.6 on 2022-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoneapp', '0004_alter_actor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
