# Generated by Django 4.0.6 on 2022-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoneapp', '0005_actor_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jfif', upload_to=''),
        ),
    ]
