# Generated by Django 4.0.6 on 2022-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoneapp', '0006_alter_actor_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
