# Generated by Django 4.0.6 on 2022-07-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testoneapp', '0008_actor_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actor',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
